### ISSUE TITLE
Crash after updating to sodiumcoreshadersupport-1.1.0-sodium0.5.11

### ISSUE THREAD

**Issue by vico93** [lni-dev/SodiumCoreShaderSupport#2]
Got [this crash](https://gist.github.com/vico93/60312a12e139c909af1d71106094f805) after updating the mod to the latest version on Modrinth.

Running on 1.21.1

**Comment by lni-dev** [comment]
I will check it tomorrow, when does this crash happen? while starting the game?

**Comment by vico93** [comment]
> I will check it tomorrow, when does this crash happen? while starting the game?

Yep, the game didnt even boot

**Comment by lni-dev** [comment]
Should be fixed now with version 1.1.1. It is already on modrinth. I was just wondering tho, are you working on a resourcepack which supports sodium shaders?
